### PR TITLE
Changed formatter to inherited from BaseFormatter

### PR DESCRIPTION
**Pull request by alex-slynko**
* This will help to use multiple formatters. I.e. documentation
* Also fixed rspec_1 support

### CODE REVIEW

**Comment by grosser** [comment]
yeah good point, it should not force dots ...

can you change the require to `Gem::Specification.find_all_by_name('rspec-core').first.try(:version)` instead of raising and then rescuing ... ideally make a test that fails without it ... but don't worry if that's to complicated ...

**Comment by alex-slynko** [comment]
I could not use try, but this way it works.

**Comment by grosser** [comment]
❤️

**Comment by grosser** [comment]
1.0.0 is out

**Pull request merged**
